# grader: I built this for you.  -1
# grader: No external documentation.  -10

CPPFLAGS=-Wall

.PHONY: runC
runC: dearrangement
	dearrangement

.PHONY: runP
runP: 
	python dearrangement.py

.PHONY: clean
clean:
	rm dearrangement
